### ISSUE TITLE
Improving Julia implementation

### ISSUE THREAD

**Issue by JamieMair** [diehlpk/async_heat_equation#5]
There has been some interest in your recent arXiv paper on the [Julia discourse forum](https://discourse.julialang.org/t/benchmarking-the-parallel-1d-heat-equation-solver-in-chapel-charm-c-hpx-go-julia-python-rust-swift-and-java/101330). 

I think the community would like to help you work on the Julia implementation (if that is wanted). I have created a fork and worked on some of the Julia code (only `monte/monte.jl` and `util.jl` and `heat/heat.jl`) in [this branch](https://github.com/JamieMair/async_heat_equation/tree/improvements-to-julia-implementation). I have just added some minor tweaks to follow the standard [performance tips](https://docs.julialang.org/en/v1/manual/performance-tips/) and benchmarking best practices for a fair comparison with other languages. We would like to continue this work, but could you please direct us to the file that is most important for your tests, as there are several files called `heat_ghosts*.jl`?

**Comment by diehlpk** [comment]
@JamieMair sure, that is appreciated.

Please do all pull request and we will add the new code. 

I like the idea with Julia (native) and I think we will add that to the figure. 

Please note that we did not optimize the other codes and most of them are a native version.

**Comment by diehlpk** [comment]
@JamieMair we work on a follow-up paper where we compared HPX, Chapel, Charm++, and Julia for distributed runs. 

Please let me know if you or anyone would be interested in joining this benchmark paper.

**Comment by diehlpk** [comment]
We are happy to report the new improved Julia results in our talk.

**Comment by JamieMair** [comment]
> @JamieMair sure, that is appreciated.
> 
> Please do all pull request and we will add the new code.
> 
> I like the idea with Julia (native) and I think we will add that to the figure.
> 
> Please note that we did not optimize the other codes and most of them are a native version.

I have just made the PR - https://github.com/diehlpk/async_heat_equation/pull/6

Hopefully some similar improvements can be made to the more complicated algorithm in the future. Perhaps I will do that myself, if I have time to work on it. 


> @JamieMair we work on a follow-up paper where we compared HPX, Chapel, Charm++, and Julia for distributed runs.
> 
> Please let me know if you or anyone would be interested in joining this benchmark paper.

If you would like help on making sure the Julia code is representative for the benchmark comparison, I would highly recommend asking questions on the Julia discourse forum (https://discourse.julialang.org/) and making sure there are no obvious foot guns by checking the [performance tips](https://docs.julialang.org/en/v1/manual/performance-tips/). I may be able to help out on the discussions on the forum, but I am not sure I will have the time to fully commit to a new paper.

**Comment by diehlpk** [comment]
@JamieMair I asked Julia folks, however, they showed no interest or had no time. Therefore, we wrote the Julia code.

Thanks for the pull request.

Also, remember that we tried to write all codes without optimizations and not go deep into the internals to get the best performance.

**Comment by doraemonho** [comment]
Hi, I just see the paper and am quite interested to see if I could improve a bit of performance.

I am wondering how many modifications are acceptable(in terms of "without optimizations"/ code structure).

Sometimes the base library may not include all the ingredients needed for high-performance computing, and you may need a little bit more, like more aggressive SIMD ([LoopVectorization.jl](https://github.com/JuliaSIMD/LoopVectorization.jl)) or better broadcast improvement ([FastBroadcast](https://github.com/YingboMa/FastBroadcast.jl)) to further improve the performance.

**Comment by doraemonho** [comment]
Just made PR #7 , pls kindly check
Hopefully, this would settle the difference in performance expectation

**Comment by diehlpk** [comment]
`I am wondering how many modifications are acceptable(in terms of "without optimizations"/ code structure).

Sometimes the base library may not include all the ingredients needed for high-performance computing, and you may need a little bit more, like more aggressive SIMD (LoopVectorization.jl) or better broadcast improvement (FastBroadcast) to further improve the performance.`

We decided not to use SIMD, since this was not trivial for all programming languages.

We decided to only use standard library features to make a comparison of the features provided by each programming language.

@doraemonho

**Comment by doraemonho** [comment]
> `I am wondering how many modifications are acceptable(in terms of "without optimizations"/ code structure).
> 
> Sometimes the base library may not include all the ingredients needed for high-performance computing, and you may need a little bit more, like more aggressive SIMD (LoopVectorization.jl) or better broadcast improvement (FastBroadcast) to further improve the performance.`
> 
> We decided not to use SIMD, since this was not trivial for all programming languages.
> 
> We decided to only use standard library features to make a comparison of the features provided by each programming language.
> 
> @doraemonho


Get it.
That's fine for the new implementation that I submitted as they don't involve any SIMD related modification.
